language: csharp
solution: Lab1.sln

jobs:
  include:
    - dotnet: 3.1
      mono: none
      install:
      - dotnet restore
      script:
      - dotnet test

notifications:
  webhooks: 'https://shp-kursach-backend.azurewebsites.net/assignments/notify'
